import React from 'react';
import { useInventory } from '../context/InventoryContext';
import { FileText, Download, Printer } from 'lucide-react';

export const Reports: React.FC = () => {
  const { products, transactions } = useInventory();

  // Helper to generate CSV content
  const generateCSV = () => {
    const headers = ["ID", "Name", "SKU", "Category", "Vendor", "Stock", "Price"];
    const rows = products.map(p => 
      [p.id, p.name, p.sku, p.category, p.vendor, p.currentStock, p.unitPrice].join(",")
    );
    return [headers.join(","), ...rows].join("\n");
  };

  const downloadReport = () => {
    const csvContent = "data:text/csv;charset=utf-8," + encodeURI(generateCSV());
    const link = document.createElement("a");
    link.setAttribute("href", csvContent);
    link.setAttribute("download", "inventory_report.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const printReport = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center print:hidden">
        <div>
           <h2 className="text-2xl font-bold text-gray-800">Analytics & Reports</h2>
           <p className="text-gray-500 text-sm mt-1">Export your data for offline analysis</p>
        </div>
        <div className="flex space-x-3">
          <button 
            onClick={printReport}
            className="flex items-center space-x-2 bg-white text-gray-700 border border-gray-300 px-4 py-2 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <Printer size={18} />
            <span>Print / PDF</span>
          </button>
          <button 
            onClick={downloadReport}
            className="flex items-center space-x-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition-colors"
          >
            <Download size={18} />
            <span>Download CSV</span>
          </button>
        </div>
      </div>

      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 print:shadow-none print:border-none">
        <h3 className="text-lg font-semibold text-gray-800 mb-4 border-b pb-2">Inventory Summary Report</h3>
        
        <div className="grid grid-cols-3 gap-6 mb-6">
           <div className="bg-gray-50 p-4 rounded-lg">
             <p className="text-xs text-gray-500 uppercase">Total Items</p>
             <p className="text-2xl font-bold">{products.length}</p>
           </div>
           <div className="bg-gray-50 p-4 rounded-lg">
             <p className="text-xs text-gray-500 uppercase">Total Value</p>
             <p className="text-2xl font-bold">${products.reduce((acc, p) => acc + (p.currentStock * p.unitPrice), 0).toLocaleString()}</p>
           </div>
           <div className="bg-gray-50 p-4 rounded-lg">
             <p className="text-xs text-gray-500 uppercase">Transactions</p>
             <p className="text-2xl font-bold">{transactions.length}</p>
           </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="bg-gray-50 text-gray-600">
                <th className="px-4 py-2 rounded-l-lg">Product Name</th>
                <th className="px-4 py-2">Category</th>
                <th className="px-4 py-2">Vendor</th>
                <th className="px-4 py-2">Stock</th>
                <th className="px-4 py-2 rounded-r-lg">Value</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {products.map(p => (
                <tr key={p.id}>
                   <td className="px-4 py-3 font-medium">{p.name}</td>
                   <td className="px-4 py-3">{p.category}</td>
                   <td className="px-4 py-3">{p.vendor}</td>
                   <td className="px-4 py-3">{p.currentStock}</td>
                   <td className="px-4 py-3">${(p.currentStock * p.unitPrice).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      
      <div className="text-center text-xs text-gray-400 mt-8 print:block hidden">
        Report generated by SmartShelfX on {new Date().toLocaleString()}
      </div>
    </div>
  );
};